###########################################################
# LOGGER SETTINGS #
###########################################################
log_dir: "spec/log"
html_log: log.html
selenium_server_log: selenium-server.log
required_clean_logs: true
hide_datetime_from_log: true

driver: selenium

###########################################################
# MAILGUN SETTINGS                                        #
###########################################################
mailgun_key: mailgun_account_private_key
mailgun_domain: mailgun@test.domain

############################################################
# TIMEOUTS                                                 #
############################################################
timeout_tiny: 1
timeout_short: 2
timeout_small: 5
timeout_medium: 15